# TCL File Generated by Component Editor 15.1
# Sun Dec 06 19:58:13 PST 2015
# DO NOT MODIFY


# 
# tx "tx" v1.0
#  2015.12.06.19:58:13
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module tx
# 
set_module_property DESCRIPTION ""
set_module_property NAME tx
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME tx
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file alt_reset_ctrl_lego.sv SYSTEM_VERILOG PATH tx_native/alt_reset_ctrl_lego.sv TOP_LEVEL_FILE
add_fileset_file alt_reset_ctrl_tgx_cdrauto.sv SYSTEM_VERILOG PATH tx_native/alt_reset_ctrl_tgx_cdrauto.sv
add_fileset_file alt_xcvr_csr_common.sv SYSTEM_VERILOG PATH tx_native/alt_xcvr_csr_common.sv
add_fileset_file alt_xcvr_csr_common_h.sv SYSTEM_VERILOG PATH tx_native/alt_xcvr_csr_common_h.sv
add_fileset_file alt_xcvr_csr_pcs8g.sv SYSTEM_VERILOG PATH tx_native/alt_xcvr_csr_pcs8g.sv
add_fileset_file alt_xcvr_csr_pcs8g_h.sv SYSTEM_VERILOG PATH tx_native/alt_xcvr_csr_pcs8g_h.sv
add_fileset_file alt_xcvr_csr_selector.sv SYSTEM_VERILOG PATH tx_native/alt_xcvr_csr_selector.sv
add_fileset_file alt_xcvr_mgmt2dec.sv SYSTEM_VERILOG PATH tx_native/alt_xcvr_mgmt2dec.sv
add_fileset_file alt_xcvr_resync.sv SYSTEM_VERILOG PATH tx_native/alt_xcvr_resync.sv
add_fileset_file altera_wait_generate.v VERILOG PATH tx_native/altera_wait_generate.v
add_fileset_file altera_xcvr_data_adapter_av.sv SYSTEM_VERILOG PATH tx_native/altera_xcvr_data_adapter_av.sv
add_fileset_file altera_xcvr_functions.sv SYSTEM_VERILOG PATH tx_native/altera_xcvr_functions.sv
add_fileset_file altera_xcvr_native_av.sv SYSTEM_VERILOG PATH tx_native/altera_xcvr_native_av.sv
add_fileset_file altera_xcvr_native_av_functions_h.sv SYSTEM_VERILOG PATH tx_native/altera_xcvr_native_av_functions_h.sv
add_fileset_file av_hssi_8g_rx_pcs_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_8g_rx_pcs_rbc.sv
add_fileset_file av_hssi_8g_tx_pcs_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_8g_tx_pcs_rbc.sv
add_fileset_file av_hssi_common_pcs_pma_interface_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_common_pcs_pma_interface_rbc.sv
add_fileset_file av_hssi_common_pld_pcs_interface_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_common_pld_pcs_interface_rbc.sv
add_fileset_file av_hssi_pipe_gen1_2_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_pipe_gen1_2_rbc.sv
add_fileset_file av_hssi_rx_pcs_pma_interface_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_rx_pcs_pma_interface_rbc.sv
add_fileset_file av_hssi_rx_pld_pcs_interface_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_rx_pld_pcs_interface_rbc.sv
add_fileset_file av_hssi_tx_pcs_pma_interface_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_tx_pcs_pma_interface_rbc.sv
add_fileset_file av_hssi_tx_pld_pcs_interface_rbc.sv SYSTEM_VERILOG PATH tx_native/av_hssi_tx_pld_pcs_interface_rbc.sv
add_fileset_file av_pcs.sv SYSTEM_VERILOG PATH tx_native/av_pcs.sv
add_fileset_file av_pcs_ch.sv SYSTEM_VERILOG PATH tx_native/av_pcs_ch.sv
add_fileset_file av_pma.sv SYSTEM_VERILOG PATH tx_native/av_pma.sv
add_fileset_file av_reconfig_bundle_to_basic.sv SYSTEM_VERILOG PATH tx_native/av_reconfig_bundle_to_basic.sv
add_fileset_file av_reconfig_bundle_to_xcvr.sv SYSTEM_VERILOG PATH tx_native/av_reconfig_bundle_to_xcvr.sv
add_fileset_file av_rx_pma.sv SYSTEM_VERILOG PATH tx_native/av_rx_pma.sv
add_fileset_file av_tx_pma.sv SYSTEM_VERILOG PATH tx_native/av_tx_pma.sv
add_fileset_file av_tx_pma_ch.sv SYSTEM_VERILOG PATH tx_native/av_tx_pma_ch.sv
add_fileset_file av_xcvr_avmm.sv SYSTEM_VERILOG PATH tx_native/av_xcvr_avmm.sv
add_fileset_file av_xcvr_avmm_csr.sv SYSTEM_VERILOG PATH tx_native/av_xcvr_avmm_csr.sv
add_fileset_file av_xcvr_data_adapter.sv SYSTEM_VERILOG PATH tx_native/av_xcvr_data_adapter.sv
add_fileset_file av_xcvr_h.sv SYSTEM_VERILOG PATH tx_native/av_xcvr_h.sv
add_fileset_file av_xcvr_native.sv SYSTEM_VERILOG PATH tx_native/av_xcvr_native.sv
add_fileset_file av_xcvr_plls.sv SYSTEM_VERILOG PATH tx_native/av_xcvr_plls.sv
add_fileset_file sv_reconfig_bundle_merger.sv SYSTEM_VERILOG PATH tx_native/sv_reconfig_bundle_merger.sv
add_fileset_file sv_reconfig_bundle_to_ip.sv SYSTEM_VERILOG PATH tx_native/sv_reconfig_bundle_to_ip.sv
add_fileset_file sv_reconfig_bundle_to_xcvr.sv SYSTEM_VERILOG PATH tx_native/sv_reconfig_bundle_to_xcvr.sv


# 
# parameters
# 


# 
# display items
# 

