
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module C5G(

	//////////// CLOCK //////////
	input 		          		CLOCK_125_p,
	input 		          		CLOCK_50_B5B,
	input 		          		CLOCK_50_B6A,
	input 		          		CLOCK_50_B7A,
	input 		          		CLOCK_50_B8A,

	//////////// KEY //////////
	input 		          		CPU_RESET_n,
	input 		     [3:0]		KEY,

	//////////// SMA Transceiver x1 //////////
	input 		          		REFCLK_p0,
	input 		          		REFCLK_p1,
	input 		          		SMA_GXB_RX_p,
	output		          		SMA_GXB_TX_p
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
