# TCL File Generated by Component Editor 15.1
# Fri Jan 01 18:09:20 CET 2016
# DO NOT MODIFY


# 
# tx "tx" v1.0
#  2016.01.01.18:09:19
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module tx
# 
set_module_property DESCRIPTION ""
set_module_property NAME tx
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME tx
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tx
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file tx.vhd VHDL PATH tx.vhd TOP_LEVEL_FILE
add_fileset_file tx_lib.vhd VHDL PATH tx_lib.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point tx_serial_data
# 
add_interface tx_serial_data conduit end
set_interface_property tx_serial_data associatedClock ""
set_interface_property tx_serial_data associatedReset ""
set_interface_property tx_serial_data ENABLED true
set_interface_property tx_serial_data EXPORT_OF ""
set_interface_property tx_serial_data PORT_NAME_MAP ""
set_interface_property tx_serial_data CMSIS_SVD_VARIABLES ""
set_interface_property tx_serial_data SVD_ADDRESS_GROUP ""

add_interface_port tx_serial_data tx_serial_data serial_data Output 1


# 
# connection point avalon_streaming_sink_1
# 
add_interface avalon_streaming_sink_1 avalon_streaming end
set_interface_property avalon_streaming_sink_1 associatedClock clock
set_interface_property avalon_streaming_sink_1 associatedReset reset
set_interface_property avalon_streaming_sink_1 dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_1 errorDescriptor ""
set_interface_property avalon_streaming_sink_1 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_1 maxChannel 0
set_interface_property avalon_streaming_sink_1 readyLatency 0
set_interface_property avalon_streaming_sink_1 ENABLED true
set_interface_property avalon_streaming_sink_1 EXPORT_OF ""
set_interface_property avalon_streaming_sink_1 PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_1 data data Input 8
add_interface_port avalon_streaming_sink_1 error error Input 1
add_interface_port avalon_streaming_sink_1 ready ready Output 1
add_interface_port avalon_streaming_sink_1 valid valid Input 1
add_interface_port avalon_streaming_sink_1 startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink_1 endofpacket endofpacket Input 1


# 
# connection point led
# 
add_interface led conduit end
set_interface_property led associatedClock ""
set_interface_property led associatedReset ""
set_interface_property led ENABLED true
set_interface_property led EXPORT_OF ""
set_interface_property led PORT_NAME_MAP ""
set_interface_property led CMSIS_SVD_VARIABLES ""
set_interface_property led SVD_ADDRESS_GROUP ""

add_interface_port led led readdata Output 8

